services:
  hyvor-post-frontend:
    container_name: hyvor-post-frontend
    build:
      context: .
      target: frontend-dev
    volumes:
      - ./frontend:/app/frontend
      - ./shared:/app/shared
      - /app/frontend/node_modules
    labels:
      traefik.enable: true
      traefik.http.routers.hyvor-post-frontend.rule: Host(`post.hyvor.dev`)
      traefik.http.routers.hyvor-post-frontend.entrypoints: https
      traefik.http.routers.hyvor-post-frontend.tls: true
      traefik.http.routers.hyvor-post-frontend.middlewares: vite-retry@file
      traefik.http.services.hyvor-post-frontend.loadbalancer.server.port: 80

    networks:
      - hyvor-network

    profiles: [dev]

  hyvor-post-backend:
    container_name: hyvor-post-backend
    build:
      context: .
      target: backend-dev
    volumes:
      - ./backend:/app/backend
      - /app/backend/vendor
      - ../internal:/app/backend/vendor/hyvor/internal
    labels:
      traefik.enable: true
      # backend
      traefik.http.routers.hyvor-post-backend.rule: Host(`post.hyvor.dev`) && PathPrefix(`/api`)
      traefik.http.routers.hyvor-post-backend.entrypoints: https
      traefik.http.routers.hyvor-post-backend.tls: true
      traefik.http.routers.hyvor-post-backend.service: hyvor-post-backend
      # service
      traefik.http.services.hyvor-post-backend.loadbalancer.server.port: 80
    networks:
      - hyvor-network
    profiles: [dev]

networks:
  hyvor-network:
    external: true
