services:

  hyvor-post-frontend:
    container_name: hyvor-post-frontend
    build:
      context: .
      target: frontend-dev
    develop:
      watch:
        -   path: frontend/src
            action: sync
            target: /app/frontend/src
        -   path: frontend/static
            action: sync
            target: /app/frontend/static
        -   path: frontend/package.json
            action: rebuild
        -   path: frontend/package-lock.json
            action: rebuild
    labels:
      traefik.enable: true
      traefik.http.routers.hyvor-post-frontend.rule: Host(`post.hyvor.dev`)
      traefik.http.routers.hyvor-post-frontend.entrypoints: https
      traefik.http.routers.hyvor-post-frontend.tls: true
      traefik.http.routers.hyvor-post-frontend.middlewares: vite-retry@file
      traefik.http.services.hyvor-post-frontend.loadbalancer.server.port: 80

    networks:
      - hyvor-network

    profiles: [ dev ]

  hyvor-post-backend:
    container_name: hyvor-post-backend
    build:
      context: .
      target: backend-dev
    develop:
      watch:
        -   path: backend
            action: sync
            target: /app/backend
        -   path: backend/composer.lock
            action: rebuild
    labels:
      traefik.enable: true
      # backend
      traefik.http.routers.hyvor-post-backend.rule: Host(`post.hyvor.dev`) && PathPrefix(`/api`)
      traefik.http.routers.hyvor-post-backend.entrypoints: https
      traefik.http.routers.hyvor-post-backend.tls: true
      traefik.http.routers.hyvor-post-backend.service: hyvor-post-backend
      # service
      traefik.http.services.hyvor-post-backend.loadbalancer.server.port: 80
    networks:
      - hyvor-network
    profiles: [ dev ]

networks:
  hyvor-network:
    external: true
