nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: [ '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$' ]
    allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
    allow_headers: [ 'Content-Type', 'Authorization' ]
    expose_headers: [ 'Link' ]
    max_age: 3600

  paths:
    '^/api/public/':
      allow_origin: [ '*' ]
      allow_methods: [ 'GET', 'POST', 'OPTIONS', 'PATCH' ]
      max_age: 3600

    '^/api/console/':
      allow_origin: [ '*' ]
      allow_methods: [ 'GET', 'POST', 'OPTIONS', 'PATCH', 'DELETE' ]
      max_age: 3600

    '^/api/embed/':
      allow_origin: [ '*' ]
      allow_methods: [ 'GET', 'POST', 'OPTIONS', 'PATCH', 'DELETE' ]
      max_age: 3600