name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  frontend-check:
    name: "Frontend Check"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t frontend-dev . --target frontend-dev

      - name: Run Svelte Check
        run: docker run frontend-dev npm run check

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t backend-dev . --target backend-dev

      - name: Run PHPStan
        run: docker run backend-dev ./vendor/bin/phpstan analyse --memory-limit=1G --ansi

  php-tests:
    name: "PHP Tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up services
        run: |
          docker network create ci
          docker compose -f meta/ci/compose.ci.yaml up -d

      - name: Build Docker image
        run: docker build -t backend-dev . --target backend-dev

      - name: Run Tests
        run: |
          touch coverage.xml
          docker run \
          --memory=6g \
          -e DATABASE_URL="postgresql://postgres:postgres@postgres:5432/hyvor_post_testing?serverVersion=16&charset=utf8" \
          --network ci \
          --mount type=bind,source=$(pwd)/coverage.xml,target=/app/coverage.xml \
          backend-dev sh -c "
          echo "memory_limit=4096M" > /usr/local/etc/php/conf.d/99-memory.ini &&
          php -i | grep memory_limit &&
          php bin/console doctrine:migrations:migrate --no-interaction &&
          php ./vendor/bin/phpunit --coverage-clover /app/coverage.xml"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.HYVOR_ORG_CODECOV_TOKEN }}
          slug: hyvor/post
          files: /app/coverage.xml
